### ISSUE TITLE
cannot import name 'autocast' from 'torch'

### ISSUE THREAD

**Issue by TheOneTrueGuy** [pesser/stable-diffusion#14]
Got the conda env, installs, downloads and everything all working smoothly now, no error messages but upon running this pops up:

Traceback (most recent call last):
  File "stable-diffusion/scripts/txt2img.py", line 12, in <module>
    from torch import autocast
ImportError: cannot import name 'autocast' from 'torch' (/usr/local/envs/ldm/lib/python3.8/site-packages/torch/__init__.py)

**Comment by KobeAmerijckxPT** [comment]
Having the same issue currently unfortunately

**Comment by Sample-design-alt** [comment]
yes, I have the same issue for this problem.

**Comment by synaestheory** [comment]
For me, the issue was resolved by updating txt2img.py line 12 from `from torch import autocast` to `from torch.cuda.amp import autocast`.

**Comment by synaestheory** [comment]
For me, the issue was resolved by updating txt2img.py line 12 from `from torch import autocast` to `from torch.cuda.amp import autocast`.

I also needed to modify line 225 from `with precision_scope("cuda"):` to `with precision_scope(True):`. 
I am calling the CLI and passing `--precision=autocast`.
